language: csharp
mono: none
dotnet: 2.1
solution: Project.sln

before_install:
- nvm install 8.12.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
install:
- dotnet restore

script:
- dotnet build
- yarn --cwd ClientApp lint
- yarn --cwd ClientApp prettier:check
- yarn --cwd ClientApp test
- yarn --cwd ClientApp e2e

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: uniy3-project
  on: master

notifications:
  email: false
