language: csharp
mono: none
dist: xenial
dotnet: 3.1
sudo: required
solution: Project.sln
addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - ClientApp/node_modules

before_install:
- nvm install 'lts/*'
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
install:
- dotnet restore

script:
- dotnet build
- yarn --cwd ClientApp
- yarn --cwd ClientApp test
- yarn --cwd ClientApp lint
- yarn --cwd ClientApp stylelint
- yarn --cwd ClientApp prettier

notifications:
  email: false
