language: csharp
mono: none
dotnet: 2.1
solution: Project.sln

before_install:
- nvm install 8.12.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- which yarn
- yarn -v
install:
- dotnet restore

script:
- dotnet build
- yarn --cwd ClientApp test

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: uniy3-project
  on: master

notifications:
  email: false
