language: csharp
mono: none
dotnet: 2.1.200
solution: Project.sln

install:
- nvm install 8.12.0
- nvm use 8.12.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- dotnet restore

script:
- node -v
- npm -v
- yarn -v
- dotnet build
