language: csharp
mono: none
dist: xenial
dotnet: 2.2
sudo: required
solution: Project.sln
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  yarn: true
  directories:
  - ClientApp/node_modules

before_install:
- nvm install 10.15.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
install:
- dotnet restore

script:
- dotnet build
- yarn --cwd ClientApp
- yarn --cwd ClientApp test
- yarn --cwd ClientApp e2e
- yarn --cwd ClientApp prettier:check
- yarn --cwd ClientApp lint

# TODO - Fix deployment
#deploy:
#  provider: heroku
#  api_key: $HEROKU_TOKEN
#  app: uniy3-project
#  on: master

notifications:
  email: false
